[env]
TERM = "xterm-256color"

[terminal.shell]
program = "pwsh"

[window]
padding.x = 10
padding.y = 10
decorations = "Buttonless"
startup_mode = "Maximized"


[font]
normal.family = "0xProto Nerd Font Mono"
size = 15

[general]
import = [
  "C:/Users/Tented/AppData/Roaming/alacritty/themes/themes/catppuccin.toml"
]
working_directory = "C:/Users/Tented/dev"


